[package]
name = "inner-unikernel-rt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# rlibc = "1.0.0"

[profile.dev]
debug=0
panic = "abort"

[profile.release]
debug=0
panic = "abort"
