[build]
target = "x86_64-unknown-none"
rustflags = [
  "-Zthreads=8",
  "-Cforce-frame-pointers=y",
  "-Csymbol-mangling-version=v0",
  "-Ccodegen-units=1",
]

[target.x86_64-unknown-none]
linker = "clang"

[unstable]
build-std = ["core"]
