name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Log in to GitHub Docker Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: docker/setup-buildx-action@v2
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./docker/docker-linux-builder
        push: true
        tags: ghcr.io/${{ github.repository }}/runtime:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
