name: memcached_benchmark

on:
  push:
    branches: [main, ci]
    paths:
      - tools/memcached_benchmark/**
  pull_request:
    branches: [main]
    paths:
      - tools/memcached_benchmark/**

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    if: github.repository == 'rex-rs/rex'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tools/memcached_benchmark

    steps:
      - uses: actions/checkout@v4

      # Install Ubuntu dependencies
      - name: Install Ubuntu dependencies
        run: |
          sudo apt-get install -y clang pkg-config libzstd-dev mold binutils lld

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
          toolchain: nightly
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
        with:
          manifest-path: ./tools/memcached_benchmark/Cargo.toml
      - name: Build
        run: cargo build -vvv
      - name: Run tests with debug build
        run: cargo test --verbose
      - name: Run tests with release build
        run: cargo test -r --verbose
